### ISSUE TITLE
Gulp task specification error

### ISSUE THREAD

**Issue by epsilon-0** [z-edit/zedit-example-patcher#1]
The tasks defined in gulpfile.js no longer conform to the newest function standard in Gulp 4.0.

They are giving an error
```
> zedit-example-patcher@1.3.0 build C:\Users\epsilon\GIT\zedit-example-patcher
> gulp build

assert.js:350
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (C:\Users\epsilon\GIT\zedit-example-patcher\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (C:\Users\epsilon\GIT\zedit-example-patcher\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (C:\Users\epsilon\GIT\zedit-example-patcher\gulpfile.js:13:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zedit-example-patcher@1.3.0 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zedit-example-patcher@1.3.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Fix: Change the definition of the gulp tasks. I dunno exactly how.

**Comment by epsilon-0** [comment]
Fix: The new gulp file should be
```
const fs = require('fs'),
      gulp = require('gulp'),
      clean = require('gulp-clean'),
      include = require('gulp-include'),
      rename = require('gulp-rename'),
      zip = require('gulp-zip');

gulp.task('clean', gulp.series([], function() {
    return gulp.src('dist', {read: false})
        .pipe(clean());
}));

gulp.task('build', gulp.series(['clean'], function(done) {
    gulp.src('index.js')
        .pipe(include())
        .on('error', console.log)
        .pipe(gulp.dest('dist'));

    gulp.src('partials/*.html')
        .pipe(gulp.dest('dist/partials'));

    gulp.src('module.json')
        .pipe(gulp.dest('dist'));
    done();
}));

gulp.task('release', gulp.series([], function(done) {
    let moduleInfo = JSON.parse(fs.readFileSync('module.json')),
        moduleId = moduleInfo.id,
        moduleVersion = moduleInfo.version,
        zipFileName = `${moduleId}-v${moduleVersion}.zip`;

    console.log(`Packaging ${zipFileName}`);

    gulp.src('dist/**/*', { base: 'dist/'})
        .pipe(rename((path) => path.dirname = `${moduleId}/${path.dirname}`))
        .pipe(zip(zipFileName))
        .pipe(gulp.dest('.'));
    done();
}));

gulp.task('default', gulp.series(['build'], function(){}));
```

**Comment by epsilon-0** [comment]
Just opening it so that people who want to use this can see what is wrong and how to fix it.
